let product = [
    {
      id: 1,
      cate: "Giày nike",
      title: "Nike Dunk Low Green Paisley - Rep 1:1",
      price: "599,000",
      img: "./assets/images/sneaker/green-paisley.jpg",
      inCart: 0,
    },
    {
      id: 2,
      cate: "Giày nike",
      title: "SB Da Lộn Cà Phê  - Rep 1:1",
      price: "649,000",
      img: "./assets/images/sneaker/sb-caphe.jpg",
      inCart: 0,
    },
    {
      id: 3,
      cate: "Giày nike",
      title: "SB Akira Khoai Môn - Rep 1:1",
      price: "649,000",
      img: "./assets/images/sneaker/sb-khoaimon.jpg",
      inCart: 0,
    },
    {
      id: 4,
      cate: "Giày nike",
      title: "SB Akira Xanh Rêu - Rep 1:1",
      price: "649,000",
      img: "./assets/images/sneaker/sb-xanhreu.jpg",
      inCart: 0,
    },
    {
      id: 5,
      cate: "Giày nike",
      title: "SB Akira Xanh Kem - Rep 1:1",
      price: "649,000",
      img: "./assets/images/sneaker/sb-xanhkem.jpg",
      inCart: 0,
    },
    {
      id: 6,
      cate: "Giày nike",
      title: "SB Xanh Cam - Rep 1:1",
      price: "599,000",
      img: "./assets/images/sneaker/sb-xanhcam.jpg",
      inCart: 0,
    },
    {
      id: 7,
      cate: "Giày nike",
      title: "SB Hồng - Rep 1:1",
      price: "599,000",
      img: "./assets/images/sneaker/sb-hong.jpg",
      inCart: 0,
    },
    {
      id: 8,
      cate: "Giày nike",
      title: "Jordan 3 Fragment - Rep 1:1",
      price: "679,000",
      img: "./assets/images/sneaker/jordan-3.jpg",
      inCart: 0,
    },
  ]

  let newProduct = [
    {
      id: 9,
      cate: "Giày Gucci",
      title: "North Face Rhyton - Rep 1:1",
      price: "749,000",
      img: "./assets/images/sneaker/gucci-northface.jpg",
      inCart: 0,
    },
    {
      id: 10,
      cate: "Giày MLB",
      title: "Boston Monogram  - Rep 1:1",
      price: "749,000",
      img: "./assets/images/sneaker/mlb-boston.jpg",
      inCart: 0,
    },
    {
      id: 11,
      cate: "Giày nike",
      title: "Jordan 3 Retro Tinker - Rep 1:1",
      price: "679,000",
      img: "./assets/images/sneaker/jordan-3-retro.jpg",
      inCart: 0,
    },
    {
      id: 12,
      cate: "Giày nike",
      title: "Jordan Chicago Red - Rep 1:1",
      price: "749,000",
      img: "./assets/images/sneaker/jordan-chicago-cocao.jpg",
      inCart: 0,
    },
    {
      id: 13,
      cate: "Giày nike",
      title: "Jordan Legacy Blue - Rep 1:1",
      price: "749,000",
      img: "./assets/images/sneaker/jordan-lagacy-cocao.jpg",
      inCart: 0,
    },
    {
      id: 14,
      cate: "Giày nike",
      title: "Jordan Louis Vuitton - Rep 1:1",
      price: "749,000",
      img: "./assets/images/sneaker/jordan-louis-cocao.jpg",
      inCart: 0,
    },
    {
      id: 15,
      cate: "Giày nike",
      title: "Jordan Xám Đen - Rep 1:1",
      price: "649,000",
      img: "./assets/images/sneaker/jordan-xamden-cocao.jpg",
      inCart: 0,
    },
    {
      id: 16,
      cate: "Giày nike",
      title: "Jordan Xanh Ngọc - Rep 1:1",
      price: "749,000",
      img: "./assets/images/sneaker/jordan-xanhngoc-cocao.jpg",
      inCart: 0,
    },
  ]